// enum CardValues {
//   AceSpades = "AS",
//   TwoSpades = "2S",
//   ThreeSpades = "3S",
//   FourSpades = "4S",
//   FiveSpades = "5S",
//   SixSpades = "6S",
//   SevenSpades = "7S",
//   EightSpades = "8S",
//   NineSpades = "9S",
//   TenSpades = "10S",
//   JackSpades = "JS",
//   QueenSpades = "QS",
//   KingSpades = "KS",
//   AceHearts = "AH",
//   TwoHearts = "2H",
//   ThreeHearts = "3H",
//   FourHearts = "4H",
//   FiveHearts = "5H",
//   SixHearts = "6H",
//   SevenHearts = "7H",
//   EightHearts = "8H",
//   NineHearts = "9H",
//   TenHearts = "10H",
//   JackHearts = "JH",
//   QueenHearts = "QH",
//   KingHearts = "KH",
//   AceDiamonds = "AD",
//   TwoDiamonds = "2D",
//   ThreeDiamonds = "3D",
//   FourDiamonds = "4D",
//   FiveDiamonds = "5D",
//   SixDiamonds = "6D",
//   SevenDiamonds = "7D",
//   EightDiamonds = "8D",
//   NineDiamonds = "9D",
//   TenDiamonds = "10D",
//   JackDiamonds = "JD",
//   QueenDiamonds = "QD",
//   KingDiamonds = "KD",
//   AceClubs = "AC",
//   TwoClubs = "2C",
//   ThreeClubs = "3C",
//   FourClubs = "4C",
//   FiveClubs = "5C",
//   SixClubs = "6C",
//   SevenClubs = "7C",
//   EightClubs = "8C",
//   NineClubs = "9C",
//   TenClubs = "10C",
//   JackClubs = "JC",
//   QueenClubs = "QC",
//   KingClubs = "KC"
// }

// export default CardValues;

const pokerDeck = {
  '2C': [2, 'C'],
  '2D': [2, 'D'],
  '2H': [2, 'H'],
  '2S': [2, 'S'],
  '3C': [3, 'C'],
  '3D': [3, 'D'],
  '3H': [3, 'H'],
  '3S': [3, 'S'],
  '4C': [4, 'C'],
  '4D': [4, 'D'],
  '4H': [4, 'H'],
  '4S': [4, 'S'],
  '5C': [5, 'C'],
  '5D': [5, 'D'],
  '5H': [5, 'H'],
  '5S': [5, 'S'],
  '6C': [6, 'C'],
  '6D': [6, 'D'],
  '6H': [6, 'H'],
  '6S': [6, 'S'],
  '7C': [7, 'C'],
  '7D': [7, 'D'],
  '7H': [7, 'H'],
  '7S': [7, 'S'],
  '8C': [8, 'C'],
  '8D': [8, 'D'],
  '8H': [8, 'H'],
  '8S': [8, 'S'],
  '9C': [9, 'C'],
  '9D': [9, 'D'],
  '9H': [9, 'H'],
  '9S': [9, 'S'],
  '10C': [10, 'C'],
  '10D': [10, 'D'],
  '10H': [10, 'H'],
  '10S': [10, 'S'],
  'JC': [11, 'C'],
  'JD': [11, 'D'],
  'JH': [11, 'H'],
  'JS': [11, 'S'],
  'QC': [12, 'C'],
  'QD': [12, 'D'],
  'QH': [12, 'H'],
  'QS': [12, 'S'],
  'KC': [13, 'C'],
  'KD': [13, 'D'],
  'KH': [13, 'H'],
  'KS': [13, 'S'],
  'AC': [14, 'C'],
  'AD': [14, 'D'],
  'AH': [14, 'H'],
  'AS': [14, 'S']
};


export default pokerDeck