"use strict";
// enum CardValues {
//   AceSpades = "AS",
//   TwoSpades = "2S",
//   ThreeSpades = "3S",
//   FourSpades = "4S",
//   FiveSpades = "5S",
//   SixSpades = "6S",
//   SevenSpades = "7S",
//   EightSpades = "8S",
//   NineSpades = "9S",
//   TenSpades = "10S",
//   JackSpades = "JS",
//   QueenSpades = "QS",
//   KingSpades = "KS",
//   AceHearts = "AH",
//   TwoHearts = "2H",
//   ThreeHearts = "3H",
//   FourHearts = "4H",
//   FiveHearts = "5H",
//   SixHearts = "6H",
//   SevenHearts = "7H",
//   EightHearts = "8H",
//   NineHearts = "9H",
//   TenHearts = "10H",
//   JackHearts = "JH",
//   QueenHearts = "QH",
//   KingHearts = "KH",
//   AceDiamonds = "AD",
//   TwoDiamonds = "2D",
//   ThreeDiamonds = "3D",
//   FourDiamonds = "4D",
//   FiveDiamonds = "5D",
//   SixDiamonds = "6D",
//   SevenDiamonds = "7D",
//   EightDiamonds = "8D",
//   NineDiamonds = "9D",
//   TenDiamonds = "10D",
//   JackDiamonds = "JD",
//   QueenDiamonds = "QD",
//   KingDiamonds = "KD",
//   AceClubs = "AC",
//   TwoClubs = "2C",
//   ThreeClubs = "3C",
//   FourClubs = "4C",
//   FiveClubs = "5C",
//   SixClubs = "6C",
//   SevenClubs = "7C",
//   EightClubs = "8C",
//   NineClubs = "9C",
//   TenClubs = "10C",
//   JackClubs = "JC",
//   QueenClubs = "QC",
//   KingClubs = "KC"
// }
Object.defineProperty(exports, "__esModule", { value: true });
// export default CardValues;
var allCards = [
    'AS', '2S', '3S', '4S', '5S', '6S', '7S', '8S', '9S', 'TS', 'JS', 'QS', 'KS',
    'AH', '2H', '3H', '4H', '5H', '6H', '7H', '8H', '9H', 'TH', 'JH', 'QH', 'KH',
    'AD', '2D', '3D', '4D', '5D', '6D', '7D', '8D', '9D', 'TD', 'JD', 'QD', 'KD',
    'AC', '2C', '3C', '4C', '5C', '6C', '7C', '8C', '9C', 'TC', 'JC', 'QC', 'KC'
];
exports.default = allCards;
